<a href="https://colab.research.google.com/github/AbderraoufBelaiouar/PL-matches-predictor/blob/main/PL_matches_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import pandas as pd

In [1]:
import pandas as pd

In [2]:
matches=pd.read_csv('matches.csv')

In [3]:
matches.head()

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City

In [4]:
matches.shape

(1389, 28)

In [6]:
matches['team'].value_counts()

team
Manchester United           72
West Ham United             72
Newcastle United            72
Brighton and Hove Albion    72
Southampton                 72
Tottenham Hotspur           71
Manchester City             71
Leeds United                71
Wolverhampton Wanderers     71
Arsenal                     71
Crystal Palace              71
Burnley                     71
Chelsea                     70
Aston Villa                 70
Leicester City              70
Everton                     70
West Bromwich Albion        38
Fulham                      38
Liverpool                   38
Sheffield United            38
Brentford                   34
Norwich City                33
Watford                     33
Name: count, dtype: int64

In [9]:
matches[matches["team"]== "Manchester City"]

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,54,2021-05-01,12:30,Premier League,Matchweek 34,Sat,Away,W,2.0,0.0,...,Match Report,NaN,20.0,3.0,14.8,1.0,0.0,0.0,2021,Manchester City
663,56,2021-05-08,17:30,Premier League,Matchweek 35,Sat,Home,L,1.0,2.0,...,Match Report,NaN,15.0,3.0,19.0,0.0,0.0,1.0,2021,Manchester City
664,57,2021-05-14,20:00,Premier League,Matchweek 36,Fri,Away,W,4.0,3.0,...,Match Report,NaN,15.0,6.0,19.0,1.0,0.0,0.0,2021,Manchester City
665,58,2021-05-18,19:00,Premier League,Matchweek 37,Tue,Away,L,2.0,3.0,...,Match Report,NaN,8.0,4.0,13.2,1.0,0.0,0.0,2021,Manchester City
666,59,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,5.0,0.0,...,Match Report,NaN,21.0,11.0,15.3,0.0,0.0,0.0,2021,Manchester City

In [10]:
matches["round"].value_counts()

round
Matchweek 1     39
Matchweek 2     39
Matchweek 3     39
Matchweek 4     39
Matchweek 5     39
Matchweek 6     39
Matchweek 7     39
Matchweek 8     39
Matchweek 9     39
Matchweek 10    39
Matchweek 11    39
Matchweek 12    39
Matchweek 13    39
Matchweek 14    39
Matchweek 15    39
Matchweek 16    39
Matchweek 17    39
Matchweek 19    39
Matchweek 20    39
Matchweek 25    39
Matchweek 24    39
Matchweek 23    39
Matchweek 34    39
Matchweek 29    39
Matchweek 31    39
Matchweek 26    39
Matchweek 28    39
Matchweek 32    39
Matchweek 18    37
Matchweek 21    37
Matchweek 22    37
Matchweek 27    37
Matchweek 30    37
Matchweek 33    32
Matchweek 35    20
Matchweek 36    20
Matchweek 37    20
Matchweek 38    20
Name: count, dtype: int64

In [11]:
matches.dtypes

Unnamed: 0        int64
date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [14]:
matches['date']=pd.to_datetime(matches['date'])
matches.dtypes

Unnamed: 0               int64
date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                     float64
pkatt                  float64
season                   int64
team                    object
dtype: object

In [17]:
matches['venue']=matches["venue"].astype("category").cat.codes
matches.dtypes

Unnamed: 0               int64
date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                     int8
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                     float64
pkatt                  float64
season                   int64
team                    object
dtype: object

In [18]:
matches["opp_code"]=matches["opponent"].astype("category").cat.codes

In [20]:
matches["hour"]=matches["time"].str.replace(":.+","",regex=True).astype("int")
matches["hour"]

0       16
1       15
2       12
3       15
4       15
        ..
1384    19
1385    15
1386    19
1387    18
1388    16
Name: hour, Length: 1389, dtype: int64

In [22]:
matches['day_code']=matches['date'].dt.dayofweek

In [23]:
matches["target"]=(matches["result"]=="W").astype("int")

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
rf=RandomForestClassifier(n_estimators=50,min_samples_split=10,random_state=1)

In [26]:
train=matches[matches["date"]<'2022-01-01']
test=matches[matches["date"]>'2022-01-01']

In [29]:
predictors=["venue","opp_code","hour","day_code"]

In [30]:
rf.fit(train[predictors],train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [31]:
preds=rf.predict(test[predictors])

In [32]:
from sklearn.metrics import accuracy_score

In [34]:
acc=accuracy_score(test["target"],preds)
acc

0.6123188405797102

In [35]:
combined=pd.DataFrame(dict(actual=test["target"],predicted=preds))

In [36]:
pd.crosstab(index=combined["actual"],columns=combined["predicted"])

predicted    0   1
actual
0          141  31
1           76  28

In [37]:
from sklearn.metrics import precision_score

In [38]:
precision_score(test["target"],preds)

0.4745762711864407

In [40]:
grouped_matches=matches.groupby("team")

In [41]:
group=grouped_matches.get_group("Manchester City")
group

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,dist,fk,pk,pkatt,season,team,opp_code,hour,day_code,target
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,0,L,0.0,1.0,...,16.9,1.0,0.0,0.0,2022,Manchester City,18,16,6,0
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,1,W,5.0,0.0,...,17.3,1.0,0.0,0.0,2022,Manchester City,15,15,5,1
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,1,W,5.0,0.0,...,14.3,0.0,0.0,0.0,2022,Manchester City,0,12,5,1
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,0,W,1.0,0.0,...,14.0,0.0,0.0,0.0,2022,Manchester City,10,15,5,1
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,1,D,0.0,0.0,...,15.7,1.0,0.0,0.0,2022,Manchester City,17,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,54,2021-05-01,12:30,Premier League,Matchweek 34,Sat,0,W,2.0,0.0,...,14.8,1.0,0.0,0.0,2021,Manchester City,6,12,5,1
663,56,2021-05-08,17:30,Premier League,Matchweek 35,Sat,1,L,1.0,2.0,...,19.0,0.0,0.0,1.0,2021,Manchester City,5,17,5,0
664,57,2021-05-14,20:00,Premier League,Matchweek 36,Fri,0,W,4.0,3.0,...,19.0,1.0,0.0,0.0,2021,Manchester City,14,20,4,1
665,58,2021-05-18,19:00,Premier League,Matchweek 37,Tue,0,L,2.0,3.0,...,13.2,1.0,0.0,0.0,2021,Manchester City,3,19,1,0
666,59,2021-05-23,16:00,Premier League,Matchweek 38,Sun,1,W,5.0,0.0,...,15.3,0.0,0.0,0.0,2021,Manchester City,7,16,6,1

In [42]:
def rolling_averages(group,cols,new_cols):
  group=group.sort_values("date")
  rolling_stats=group[cols].rolling(3,closed='left').mean()
  group[new_cols]=rolling_stats
  group=group.dropna(subset=new_cols)
  return group

In [43]:
cols=['gf','ga','sh','sot','dist','fk','pk','pkatt']
new_cols=[f'{c}_rolling' for c in cols]

In [44]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [45]:
rolling_averages(group,cols,new_cols)

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
632,5,2020-10-17,17:30,Premier League,Matchweek 5,Sat,1,W,1.0,0.0,...,5,1,2.000000,2.333333,17.333333,4.666667,18.900000,1.333333,0.333333,0.333333
633,7,2020-10-24,12:30,Premier League,Matchweek 6,Sat,0,D,1.0,1.0,...,5,0,1.333333,2.000000,17.333333,3.666667,17.733333,0.666667,0.000000,0.000000
634,9,2020-10-31,12:30,Premier League,Matchweek 7,Sat,0,W,1.0,0.0,...,5,1,1.000000,0.666667,16.666667,4.333333,18.233333,0.666667,0.000000,0.000000
635,11,2020-11-08,16:30,Premier League,Matchweek 8,Sun,1,D,1.0,1.0,...,6,0,1.000000,0.333333,14.333333,6.666667,18.466667,1.000000,0.000000,0.000000
636,12,2020-11-21,17:30,Premier League,Matchweek 9,Sat,0,L,0.0,2.0,...,5,0,1.000000,0.666667,12.000000,5.666667,19.366667,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,42,2022-03-14,20:00,Premier League,Matchweek 29,Mon,0,D,0.0,0.0,...,0,0,2.333333,1.333333,19.000000,7.000000,15.366667,0.333333,0.333333,0.333333
29,44,2022-04-02,15:00,Premier League,Matchweek 31,Sat,0,W,2.0,0.0,...,5,1,1.666667,0.333333,18.333333,7.333333,16.000000,0.333333,0.000000,0.000000
30,46,2022-04-10,16:30,Premier League,Matchweek 32,Sun,1,D,2.0,2.0,...,6,0,2.000000,0.333333,20.000000,6.666667,16.133333,0.333333,0.000000,0.000000
31,49,2022-04-20,20:00,Premier League,Matchweek 30,Wed,1,W,3.0,0.0,...,2,1,1.333333,0.666667,15.666667,4.666667,16.700000,0.333333,0.000000,0.000000
32,50,2022-04-23,15:00,Premier League,Matchweek 34,Sat,1,W,5.0,1.0,...,5,1,2.333333,0.666667,15.333333,5.000000,17.200000,0.333333,0.000000,0.000000

In [46]:
matches_rolling=matches.groupby("team").apply(lambda x:rolling_averages(x,cols,new_cols))

/tmp/ipykernel_32965/2678141062.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  matches_rolling=matches.groupby("team").apply(lambda x:rolling_averages(x,cols,new_cols))

In [47]:
matches_rolling

                             Unnamed: 0       date   time            comp  \
team
Arsenal                 898           6 2020-10-04  14:00  Premier League
                        899           7 2020-10-17  17:30  Premier League
                        900           9 2020-10-25  19:15  Premier League
                        901          11 2020-11-01  16:30  Premier League
                        902          13 2020-11-08  19:15  Premier League
...                                 ...        ...    ...             ...
Wolverhampton Wanderers 227          32 2022-03-13  14:00  Premier League
                        228          33 2022-03-18  20:00  Premier League
                        229          34 2022-04-02  15:00  Premier League
                        230          35 2022-04-08  20:00  Premier League
                        231          36 2022-04-24  14:00  Premier League

                                    round  day  venue result   gf   ga  ...  \
team                                                                    ...
Arsenal                 898   Matchweek 4  Sun      1      W  2.0  1.0  ...
                        899   Matchweek 5  Sat      0      L  0.0  1.0  ...
                        900   Matchweek 6  Sun      1      L  0.0  1.0  ...
                        901   Matchweek 7  Sun      0      W  1.0  0.0  ...
                        902   Matchweek 8  Sun      1      L  0.0  3.0  ...
...                                   ...  ...    ...    ...  ...  ...  ...
Wolverhampton Wanderers 227  Matchweek 29  Sun      0      W  1.0  0.0  ...
                        228  Matchweek 30  Fri      1      L  2.0  3.0  ...
                        229  Matchweek 31  Sat      1      W  2.0  1.0  ...
                        230  Matchweek 32  Fri      0      L  0.0  1.0  ...
                        231  Matchweek 34  Sun      0      L  0.0  1.0  ...

                            day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 898        6       1    2.000000    1.333333
                        899        5       0    1.666667    1.666667
                        900        6       0    1.000000    1.666667
                        901        6       1    0.666667    1.000000
                        902        6       0    0.333333    0.666667
...                              ...     ...         ...         ...
Wolverhampton Wanderers 227        6       1    1.333333    1.000000
                        228        4       0    1.666667    0.666667
                        229        5       1    2.333333    1.000000
                        230        4       0    1.666667    1.333333
                        231        6       0    1.333333    1.666667

                             sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 898    7.666667    3.666667    14.733333   0.666667
                        899    5.333333    3.666667    15.766667   0.000000
                        900    7.000000    3.666667    16.733333   0.666667
                        901    9.666667    4.000000    16.033333   1.000000
                        902    9.666667    2.666667    18.033333   1.000000
...                                 ...         ...          ...        ...
Wolverhampton Wanderers 227   12.333333    3.666667    19.300000   0.000000
                        228   12.333333    4.333333    19.600000   0.000000
                        229   13.000000    5.333333    19.833333   0.000000
                        230   13.000000    5.000000    18.533333   0.000000
                        231   10.000000    4.666667    17.633333   0.000000

                            pk_rolling  pkatt_rolling
team
Arsenal                 898   0.000000       0.000000
                        899   0.000000       0.000000
                        900   0.000000       0.000000
                        901   0.000000       0.000000
                        902   0.333333       0.333333
...                                ...            ...
Wolverhampton Wanderers 227   0.000000       0.000000
                        228   0.000000       0.000000
                        229   0.000000       0.000000
                        230   0.000000       0.000000
                        231   0.000000       0.000000

[1317 rows x 40 columns]

In [48]:
matches_rolling=matches_rolling.droplevel('team')

In [49]:
matches_rolling

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
898,6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,1,W,2.0,1.0,...,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
899,7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,0,L,0.0,1.0,...,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
900,9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,1,L,0.0,1.0,...,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
901,11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,0,W,1.0,0.0,...,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
902,13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,1,L,0.0,3.0,...,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,32,2022-03-13,14:00,Premier League,Matchweek 29,Sun,0,W,1.0,0.0,...,6,1,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
228,33,2022-03-18,20:00,Premier League,Matchweek 30,Fri,1,L,2.0,3.0,...,4,0,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
229,34,2022-04-02,15:00,Premier League,Matchweek 31,Sat,1,W,2.0,1.0,...,5,1,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
230,35,2022-04-08,20:00,Premier League,Matchweek 32,Fri,0,L,0.0,1.0,...,4,0,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
231,36,2022-04-24,14:00,Premier League,Matchweek 34,Sun,0,L,0.0,1.0,...,6,0,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [50]:
matches_rolling.index=range(matches_rolling.shape[0])

In [51]:
matches_rolling

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,1,W,2.0,1.0,...,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
1,7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,0,L,0.0,1.0,...,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
2,9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,1,L,0.0,1.0,...,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
3,11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,0,W,1.0,0.0,...,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
4,13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,1,L,0.0,3.0,...,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1312,32,2022-03-13,14:00,Premier League,Matchweek 29,Sun,0,W,1.0,0.0,...,6,1,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
1313,33,2022-03-18,20:00,Premier League,Matchweek 30,Fri,1,L,2.0,3.0,...,4,0,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
1314,34,2022-04-02,15:00,Premier League,Matchweek 31,Sat,1,W,2.0,1.0,...,5,1,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
1315,35,2022-04-08,20:00,Premier League,Matchweek 32,Fri,0,L,0.0,1.0,...,4,0,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
1316,36,2022-04-24,14:00,Premier League,Matchweek 34,Sun,0,L,0.0,1.0,...,6,0,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [52]:
def make_predictions(data,predictors):
  train=data[data["date"]<'2022-01-01']
  test=data[data["date"]>'2022-01-01']
  rf.fit(train[predictors],train["target"])
  preds=rf.predict(test[predictors])
  combined=pd.DataFrame(dict(actual=test["target"],predicted=preds),index=test.index)
  precision=precision_score(test["target"],preds)
  return combined,precision

In [53]:
combined,precision=make_predictions(matches_rolling,predictors+ new_cols)

In [54]:
precision

0.625

In [55]:
combined=combined.merge(matches_rolling[["date","team","opponent","result"]],left_index=True,right_index=True)

In [56]:
combined

,actual,predicted,date,team,opponent,result
55,0,0,2022-01-23,Arsenal,Burnley,D
56,1,0,2022-02-10,Arsenal,Wolves,W
57,1,0,2022-02-19,Arsenal,Brentford,W
58,1,1,2022-02-24,Arsenal,Wolves,W
59,1,1,2022-03-06,Arsenal,Watford,W
...,...,...,...,...,...,...
1312,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W
1313,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L
1314,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W
1315,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L
1316,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L

In [59]:
class MissingDict(dict):
  __missing__=lambda self,key:key
map_values={
    "Manchester City":"Man City",
    "Manchester United":"Man United",
    "Newcastle United":"Newcastle",
    "Tottenham Hotspur":"Tottenham"
}
mapping=MissingDict(**map_values)
mapping['Manchester City']

'Man City'

In [60]:
combined["new_team"]=combined["team"].map(mapping)
combined

,actual,predicted,date,team,opponent,result,new_team
55,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal
56,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal
57,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal
58,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal
59,1,1,2022-03-06,Arsenal,Watford,W,Arsenal
...,...,...,...,...,...,...,...
1312,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W,Wolverhampton Wanderers
1313,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L,Wolverhampton Wanderers
1314,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W,Wolverhampton Wanderers
1315,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L,Wolverhampton Wanderers
1316,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolverhampton Wanderers

In [61]:
merged=combined.merge(combined,left_on=["date","new_team"],right_on=["date","opponent"])
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolverhampton Wanderers
2,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
3,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolverhampton Wanderers
4,1,1,2022-03-06,Arsenal,Watford,W,Arsenal,0,0,Watford,Arsenal,L,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,0,0,2022-03-10,Watford,Wolves,L,Watford,1,0,Wolverhampton Wanderers,Watford,W,Wolverhampton Wanderers
174,1,0,2022-03-13,Watford,Southampton,W,Watford,0,0,Southampton,Watford,L,Southampton
175,0,0,2022-04-09,Watford,Leeds United,L,Watford,1,0,Leeds United,Watford,W,Leeds United
176,0,0,2022-04-16,Watford,Brentford,L,Watford,1,0,Brentford,Watford,W,Brentford
177,0,0,2022-04-23,Watford,Manchester City,L,Watford,1,1,Manchester City,Watford,W,Man City

In [64]:
merged[(merged['predicted_x']==1) & (merged['predicted_y']==0)]['actual_x'].value_counts()

actual_x
1    12
0     7
Name: count, dtype: int64

In [65]:
12/19

0.631578947368421